name: PCPBREALTY
favicon: null
layout_spectrum: 0.041875371942296624
typography_spectrum: 0.17693707975558937
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: REAL ESTATE TRAVELING
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.981170195620507
  lightness: 0.28044343437068164
  saturation: 0.6262822069693357
  rhythmicContrast: 0.9368990657385439
purpose: []
