favicon: null
name: PCPBREALTY
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5854517789557576
  brandStrength: 0.5570267227012664
  rhythmicContrast: 0.06265167752280831
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.5346394216176122
typography_spectrum: 0.2701396
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.7255628153216094
analytics:
  twitter: null
  google: null
  facebook: null
